import media from "@/data/media.generated.json";
import { isUploadKey, readUpload, uploadIdFromKey } from "./uploads";
import { asset } from "./asset";

type MediaEntry = { w: number; h: number; widths: number[]; kind: "packshot" | "render" | "photo" };

const table = media as Record<string, MediaEntry>;

export type ImageSource = {
  src: string;
  /** Omitted for uploads, which have a single data: URL. */
  srcSet?: string;
  width: number;
  height: number;
  kind: MediaEntry["kind"];
};

/** Responsive sources for an image generated by scripts/prepare-images.mjs. */
export function imageSource(key: string): ImageSource {
  const entry = table[key];
  if (!entry) throw new Error(`Unknown image "${key}". Run npm run media:images.`);
  const url = (w: number) => asset(`/images/${key}-${w}.webp`);
  const largest = entry.widths[entry.widths.length - 1];
  const mid = entry.widths[Math.min(1, entry.widths.length - 1)];
  return {
    src: url(mid ?? largest),
    srcSet: entry.widths.map((w) => `${url(w)} ${w}w`).join(", "),
    width: entry.w,
    height: entry.h,
    kind: entry.kind,
  };
}

/**
 * Resolves an image key to a usable source: a manifest image, an admin upload ("u:<id>"),
 * or null when it is unknown (a deleted upload, a bad key). Never throws, so a missing image
 * degrades to an empty tile instead of breaking the page.
 */
export function resolveImage(key: string): ImageSource | null {
  if (isUploadKey(key)) {
    const upload = readUpload(uploadIdFromKey(key));
    if (!upload) return null;
    return { src: upload.data, srcSet: undefined, width: upload.w, height: upload.h, kind: upload.kind };
  }
  if (key in table) return imageSource(key);
  return null;
}

export const hasImage = (key: string): boolean =>
  key in table || (isUploadKey(key) && readUpload(uploadIdFromKey(key)) !== null);
