import media from "@/data/media.generated.json";
import { asset } from "./asset";

type MediaEntry = { w: number; h: number; widths: number[]; kind: "packshot" | "render" | "photo" };

const table = media as Record<string, MediaEntry>;

export type ImageSource = {
  src: string;
  srcSet: string;
  width: number;
  height: number;
  kind: MediaEntry["kind"];
};

/** Responsive sources for an image generated by scripts/prepare-images.mjs. */
export function imageSource(key: string): ImageSource {
  const entry = table[key];
  if (!entry) throw new Error(`Unknown image "${key}". Run npm run media:images.`);
  const url = (w: number) => asset(`/images/${key}-${w}.webp`);
  const largest = entry.widths[entry.widths.length - 1];
  const mid = entry.widths[Math.min(1, entry.widths.length - 1)];
  return {
    src: url(mid ?? largest),
    srcSet: entry.widths.map((w) => `${url(w)} ${w}w`).join(", "),
    width: entry.w,
    height: entry.h,
    kind: entry.kind,
  };
}

export const hasImage = (key: string) => key in table;
