// Vectorises the Mystic Sand logo (black line art on Sand) and renders the app icons.
// Usage: node scripts/trace-logo.mjs
// Prefer a real vector logo from the client when available; this is the fallback.
import fs from "node:fs/promises";
import path from "node:path";
import Potrace from "oslllo-potrace";
import sharp from "sharp";
import { LOGO_SOURCE, photo, WEB_DIR } from "./media-manifest.mjs";

const SAND = "#CBBD93";
const INK = "#141412";

async function main() {
  const src = photo(LOGO_SOURCE);
  const { data, info } = await sharp(src).greyscale().threshold(110).raw().toBuffer({ resolveWithObject: true });
  const { width, height } = info;

  // Row profile of ink pixels: the mark and the wordmark are separated by an empty band.
  const rows = new Array(height).fill(0);
  const cols = new Array(width).fill(0);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      if (data[y * width + x] === 0) {
        rows[y]++;
        cols[x]++;
      }
    }
  }
  const inked = (n) => n > 0;
  const top = rows.findIndex(inked);
  const bottom = height - 1 - [...rows].reverse().findIndex(inked);
  const left = cols.findIndex(inked);
  const right = width - 1 - [...cols].reverse().findIndex(inked);

  // Largest empty gap between top and bottom = split between mark and wordmark.
  let gapStart = -1;
  let gapLen = 0;
  for (let y = top, run = 0; y <= bottom; y++) {
    if (rows[y] === 0) {
      run++;
      if (run > gapLen) {
        gapLen = run;
        gapStart = y - run + 1;
      }
    } else run = 0;
  }
  const markBottom = gapStart - 1;
  const wordTop = gapStart + gapLen;

  // Horizontal extent of the mark alone.
  let markLeft = width;
  let markRight = 0;
  for (let y = top; y <= markBottom; y++) {
    for (let x = 0; x < width; x++) {
      if (data[y * width + x] === 0) {
        markLeft = Math.min(markLeft, x);
        markRight = Math.max(markRight, x);
      }
    }
  }

  const bw = await sharp(src).greyscale().threshold(110).png().toBuffer();
  const svg = await Potrace(bw, {
    turdsize: 6,
    optcurve: true,
    alphamax: 1,
    opttolerance: 0.2,
  }).trace();
  const d = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]).join(" ");
  if (!d) throw new Error("Potrace returned no path");

  const pad = 2;
  const box = (x0, y0, x1, y1) => [x0 - pad, y0 - pad, x1 - x0 + 1 + pad * 2, y1 - y0 + 1 + pad * 2];
  const viewBoxes = {
    full: box(left, top, right, bottom),
    mark: box(markLeft, top, markRight, markBottom),
    wordmark: box(left, wordTop, right, bottom),
  };

  const ts = `// Generated by scripts/trace-logo.mjs from the client's logo artwork. Do not edit.
export const LOGO_PATH = ${JSON.stringify(d)};

export const LOGO_VIEWBOX = {
  full: ${JSON.stringify(viewBoxes.full.join(" "))},
  mark: ${JSON.stringify(viewBoxes.mark.join(" "))},
  wordmark: ${JSON.stringify(viewBoxes.wordmark.join(" "))},
} as const;
`;
  const tsFile = path.join(WEB_DIR, "src", "components", "brand", "logo-path.generated.ts");
  await fs.mkdir(path.dirname(tsFile), { recursive: true });
  await fs.writeFile(tsFile, ts);

  const svgFor = (vb, fill, bg) => {
    const [x, y, w, h] = vb;
    const bgRect = bg ? `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${bg}"/>` : "";
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x} ${y} ${w} ${h}">${bgRect}<path d="${d}" fill="${fill}" fill-rule="evenodd"/></svg>`;
  };

  // App icons: the hourglass mark on Sand (the Instagram look).
  const icon = async (size, file, markScale) => {
    const markSvg = Buffer.from(svgFor(viewBoxes.mark, INK));
    const inner = Math.round(size * markScale);
    const mark = await sharp(markSvg, { density: 600 }).resize(inner, inner, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } }).png().toBuffer();
    await sharp({ create: { width: size, height: size, channels: 4, background: SAND } })
      .composite([{ input: mark, gravity: "center" }])
      .png()
      .toFile(file);
  };
  await icon(256, path.join(WEB_DIR, "src", "app", "icon.png"), 0.6);
  await icon(180, path.join(WEB_DIR, "src", "app", "apple-icon.png"), 0.58);

  // Open Graph image (link previews, e.g. when the demo link is shared on WhatsApp).
  const lockup = await sharp(Buffer.from(svgFor(viewBoxes.full, INK)), { density: 600 })
    .resize(520, 300, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();
  await sharp({ create: { width: 1200, height: 630, channels: 4, background: SAND } })
    .composite([{ input: lockup, gravity: "center" }])
    .png()
    .toFile(path.join(WEB_DIR, "src", "app", "[locale]", "opengraph-image.png"));

  // Keep an SVG copy for reference / reuse.
  await fs.mkdir(path.join(WEB_DIR, "public", "brand"), { recursive: true });
  await fs.writeFile(path.join(WEB_DIR, "public", "brand", "logo.svg"), svgFor(viewBoxes.full, INK));

  console.log("✓ logo traced", viewBoxes);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
