import { cn } from "@/lib/cn";
import { resolveImage } from "@/lib/media";

type Props = {
  image: string;
  alt: string;
  /** Rendered width hint, e.g. "(min-width: 1024px) 25vw, 50vw". */
  sizes: string;
  className?: string;
  /** Above-the-fold images: eager + high fetch priority. */
  priority?: boolean;
  fit?: "cover" | "contain";
  /** Studio packshots: dissolve the light backdrop into the tile colour. */
  blend?: boolean;
  style?: React.CSSProperties;
};

/** <img srcset> over the WebP files generated by scripts/prepare-images.mjs (or an upload). */
export function ResponsiveImage({ image, alt, sizes, className, priority = false, fit = "cover", blend, style }: Props) {
  const src = resolveImage(image);
  // Unknown key (deleted upload, bad reference): an empty tile, keeping the sizing classes.
  if (!src) {
    return <span aria-hidden className={cn("block h-full w-full bg-tile", className)} style={style} />;
  }
  const shouldBlend = blend ?? src.kind === "packshot";
  return (
    // eslint-disable-next-line @next/next/no-img-element -- static export; srcset is pre-generated
    <img
      src={src.src}
      srcSet={src.srcSet}
      sizes={sizes}
      width={src.width}
      height={src.height}
      alt={alt}
      loading={priority ? "eager" : "lazy"}
      decoding={priority ? "sync" : "async"}
      fetchPriority={priority ? "high" : undefined}
      className={cn(
        "h-full w-full",
        fit === "cover" ? "object-cover" : "object-contain",
        shouldBlend && "mix-blend-multiply",
        className,
      )}
      style={style}
    />
  );
}
